/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;

/**
 *
 * @author Ramos
 */
public class TelaLivro extends javax.swing.JFrame {

    /**
     * Creates new form TelaLivro
     */

    public TelaLivro(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
    }
    private Usuario usuario;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        autorTextField = new javax.swing.JTextField();
        tituloTextField = new javax.swing.JTextField();
        generoComboBox = new javax.swing.JComboBox<>();
        notaComboBox = new javax.swing.JComboBox<>();
        cadastrarButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Livro");

        autorTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Autor"));

        tituloTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Título"));

        generoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ficção", "Romance", "Técnico" }));
        generoComboBox.setToolTipText("Gênero");
        generoComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Gênero"));

        notaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.0", "1.5", "2.0", "2.5", "3.0", "3.5", "4.0", "4.5", "5.0", "5.5", "6.0", "6.5", "7.0", "7.5", "8.0", "8.5", "9.0", "9.5", "10.0" }));
        notaComboBox.setToolTipText("Gênero");
        notaComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota"));

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastrarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarButton))
                    .addComponent(autorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(autorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(generoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(notaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarButton)
                    .addComponent(voltarButton))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        this.dispose();
        new TelaUsuario(usuario).setVisible(true);
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        
        var autor = autorTextField.getText();
        var titulo = tituloTextField.getText();
        var genero = (String)generoComboBox.getSelectedItem();
        var notaString = (String)notaComboBox.getSelectedItem();

        if(autor == null || autor.length() == 0 || titulo == null || titulo.length() == 0 || genero == null || genero.length() == 0 || notaString == null || notaString.length() == 0){
            JOptionPane.showMessageDialog(null, "Por favor insira as informações corretamente... preencha todos os campos!");
        }
        else {
            try {
                var livro = new Livro(titulo, autor);
                var livroDAO = new LivroDAO();
                var av = new Avaliacao();
                var nota = Double.parseDouble(notaString);
                
                if(livroDAO.existeLivro(livro)){
                    JOptionPane.showMessageDialog(null, "Livro já existente!");
                }
                else {
                    livro.setGenero(genero);
                    livro.setNotaMedia(nota);
                    livro.setFk_IdUser(usuario.getId());

                    av.setNota(nota);
                    av.setFk_IdUser(usuario.getId());

                    try{

                        livroDAO.cadastrar(livro);
                        livro = livroDAO.getLivro(titulo, autor);
                        av.setFk_IdLivro(livro.getId());
                        var avDAO = new AvaliacaoDAO();
                        avDAO.cadastrar(av);

                        autorTextField.setText("");
                        tituloTextField.setText("");
                        generoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ficção", "Romance", "Técnico" }));
                        notaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.0", "1.5", "2.0", "2.5", "3.0", "3.5", "4.0", "4.5", "5.0", "5.5", "6.0", "6.5", "7.0", "7.5", "8.0", "8.5", "9.0", "9.5", "10.0" }));
                    
                        JOptionPane.showMessageDialog(null, "Livro cadastrado com sucesso!");
                    
                    }
                    catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Ocorreu um erro ao cadastrar...");
                        e.printStackTrace();
                    }
                }

            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao cadastrar...");
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_cadastrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autorTextField;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JComboBox<String> generoComboBox;
    private javax.swing.JComboBox<String> notaComboBox;
    private javax.swing.JTextField tituloTextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
